export interface Hashtag {
  tag: string;
  popularity: number;
}

export interface HashtagCategory {
  name: string;
  keywords: string[];
  hashtags: Hashtag[];
}

export const categories: HashtagCategory[] = [
  {
    name: 'fitness',
    keywords: ['fitness', 'gym', 'workout', 'exercise', 'training', 'muscle', 'bodybuilding', 'crossfit', 'weightlifting'],
    hashtags: [
      { tag: 'fitness', popularity: 98 }, { tag: 'gym', popularity: 96 }, { tag: 'workout', popularity: 95 },
      { tag: 'fitnessmotivation', popularity: 92 }, { tag: 'fit', popularity: 90 }, { tag: 'training', popularity: 88 },
      { tag: 'bodybuilding', popularity: 85 }, { tag: 'fitfam', popularity: 84 }, { tag: 'gymlife', popularity: 82 },
      { tag: 'exercise', popularity: 80 }, { tag: 'personaltrainer', popularity: 75 }, { tag: 'crossfit', popularity: 73 },
      { tag: 'fitnessjourney', popularity: 72 }, { tag: 'gymmotivation', popularity: 70 }, { tag: 'weightlifting', popularity: 68 },
      { tag: 'strengthtraining', popularity: 65 }, { tag: 'fitlife', popularity: 63 }, { tag: 'workoutmotivation', popularity: 60 },
      { tag: 'fitnessaddict', popularity: 58 }, { tag: 'legday', popularity: 55 }, { tag: 'gains', popularity: 53 },
      { tag: 'cardio', popularity: 50 }, { tag: 'homeworkout', popularity: 48 }, { tag: 'fitnessmodel', popularity: 45 },
      { tag: 'abs', popularity: 42 },
    ],
  },
  {
    name: 'food',
    keywords: ['food', 'cooking', 'recipe', 'eat', 'meal', 'chef', 'baking', 'kitchen', 'dinner', 'lunch'],
    hashtags: [
      { tag: 'food', popularity: 98 }, { tag: 'foodie', popularity: 96 }, { tag: 'foodporn', popularity: 94 },
      { tag: 'instafood', popularity: 92 }, { tag: 'yummy', popularity: 90 }, { tag: 'delicious', popularity: 88 },
      { tag: 'homemade', popularity: 85 }, { tag: 'cooking', popularity: 83 }, { tag: 'recipe', popularity: 82 },
      { tag: 'foodphotography', popularity: 80 }, { tag: 'foodstagram', popularity: 78 }, { tag: 'healthyfood', popularity: 76 },
      { tag: 'dinner', popularity: 74 }, { tag: 'lunch', popularity: 72 }, { tag: 'breakfast', popularity: 70 },
      { tag: 'foodlover', popularity: 68 }, { tag: 'baking', popularity: 65 }, { tag: 'chef', popularity: 63 },
      { tag: 'homecooking', popularity: 60 }, { tag: 'mealprep', popularity: 58 }, { tag: 'vegan', popularity: 55 },
      { tag: 'vegetarian', popularity: 52 }, { tag: 'dessert', popularity: 50 }, { tag: 'brunch', popularity: 48 },
      { tag: 'foodblogger', popularity: 45 },
    ],
  },
  {
    name: 'travel',
    keywords: ['travel', 'vacation', 'trip', 'adventure', 'explore', 'wanderlust', 'tourism', 'destination', 'backpacking'],
    hashtags: [
      { tag: 'travel', popularity: 98 }, { tag: 'travelgram', popularity: 95 }, { tag: 'traveling', popularity: 93 },
      { tag: 'wanderlust', popularity: 92 }, { tag: 'adventure', popularity: 90 }, { tag: 'explore', popularity: 88 },
      { tag: 'travelphotography', popularity: 86 }, { tag: 'instatravel', popularity: 84 }, { tag: 'vacation', popularity: 82 },
      { tag: 'traveltheworld', popularity: 80 }, { tag: 'trip', popularity: 78 }, { tag: 'travelblogger', popularity: 76 },
      { tag: 'tourism', popularity: 74 }, { tag: 'backpacking', popularity: 72 }, { tag: 'roadtrip', popularity: 70 },
      { tag: 'traveladdict', popularity: 68 }, { tag: 'traveler', popularity: 65 }, { tag: 'solotravel', popularity: 63 },
      { tag: 'travellife', popularity: 60 }, { tag: 'globetrotter', popularity: 58 }, { tag: 'exploremore', popularity: 55 },
      { tag: 'travelholic', popularity: 52 }, { tag: 'passport', popularity: 50 }, { tag: 'bucketlist', popularity: 48 },
      { tag: 'digitalnomad', popularity: 45 },
    ],
  },
  {
    name: 'fashion',
    keywords: ['fashion', 'style', 'outfit', 'clothing', 'dress', 'wear', 'trendy', 'ootd', 'streetwear'],
    hashtags: [
      { tag: 'fashion', popularity: 98 }, { tag: 'style', popularity: 96 }, { tag: 'ootd', popularity: 94 },
      { tag: 'fashionblogger', popularity: 92 }, { tag: 'outfit', popularity: 90 }, { tag: 'streetstyle', popularity: 88 },
      { tag: 'fashionista', popularity: 86 }, { tag: 'instafashion', popularity: 84 }, { tag: 'outfitoftheday', popularity: 82 },
      { tag: 'fashionstyle', popularity: 80 }, { tag: 'streetwear', popularity: 78 }, { tag: 'trendy', popularity: 76 },
      { tag: 'lookoftheday', popularity: 74 }, { tag: 'fashiondesigner', popularity: 72 }, { tag: 'clothing', popularity: 70 },
      { tag: 'styleinspo', popularity: 68 }, { tag: 'outfitinspo', popularity: 65 }, { tag: 'fashionable', popularity: 63 },
      { tag: 'mensfashion', popularity: 60 }, { tag: 'womensfashion', popularity: 58 }, { tag: 'fashionweek', popularity: 55 },
      { tag: 'vintage', popularity: 52 }, { tag: 'accessories', popularity: 50 }, { tag: 'shoes', popularity: 48 },
    ],
  },
  {
    name: 'beauty',
    keywords: ['beauty', 'makeup', 'skincare', 'cosmetics', 'hair', 'nails', 'glow', 'lipstick', 'foundation'],
    hashtags: [
      { tag: 'beauty', popularity: 98 }, { tag: 'makeup', popularity: 96 }, { tag: 'skincare', popularity: 94 },
      { tag: 'beautyblogger', popularity: 90 }, { tag: 'makeupartist', popularity: 88 }, { tag: 'cosmetics', popularity: 85 },
      { tag: 'skincareroutine', popularity: 83 }, { tag: 'beautytips', popularity: 80 }, { tag: 'hair', popularity: 78 },
      { tag: 'nails', popularity: 76 }, { tag: 'glam', popularity: 74 }, { tag: 'makeuptutorial', popularity: 72 },
      { tag: 'hairstyle', popularity: 70 }, { tag: 'lipstick', popularity: 68 }, { tag: 'foundation', popularity: 65 },
      { tag: 'beautycare', popularity: 63 }, { tag: 'naturalbeauty', popularity: 60 }, { tag: 'skincareproducts', popularity: 58 },
      { tag: 'makeuplover', popularity: 55 }, { tag: 'beautycommunity', popularity: 52 }, { tag: 'nailart', popularity: 50 },
      { tag: 'haircare', popularity: 48 }, { tag: 'glow', popularity: 45 },
    ],
  },
  {
    name: 'photography',
    keywords: ['photography', 'photo', 'camera', 'photographer', 'portrait', 'landscape', 'canon', 'nikon', 'sony'],
    hashtags: [
      { tag: 'photography', popularity: 98 }, { tag: 'photooftheday', popularity: 96 }, { tag: 'photographer', popularity: 94 },
      { tag: 'photo', popularity: 92 }, { tag: 'portrait', popularity: 88 }, { tag: 'landscape', popularity: 86 },
      { tag: 'naturephotography', popularity: 84 }, { tag: 'streetphotography', popularity: 82 }, { tag: 'canon', popularity: 80 },
      { tag: 'nikon', popularity: 78 }, { tag: 'sony', popularity: 76 }, { tag: 'photographylovers', popularity: 74 },
      { tag: 'portraitphotography', popularity: 72 }, { tag: 'landscapephotography', popularity: 70 }, { tag: 'photoshoot', popularity: 68 },
      { tag: 'photographyislife', popularity: 65 }, { tag: 'goldenhour', popularity: 63 }, { tag: 'lightroom', popularity: 60 },
      { tag: 'photoshop', popularity: 58 }, { tag: 'cameragear', popularity: 55 }, { tag: 'shotoniphone', popularity: 52 },
      { tag: 'dronephotography', popularity: 50 }, { tag: 'blackandwhite', popularity: 48 },
    ],
  },
  {
    name: 'business',
    keywords: ['business', 'entrepreneur', 'startup', 'company', 'ceo', 'hustle', 'money', 'success', 'leadership'],
    hashtags: [
      { tag: 'business', popularity: 96 }, { tag: 'entrepreneur', popularity: 94 }, { tag: 'startup', popularity: 92 },
      { tag: 'success', popularity: 90 }, { tag: 'motivation', popularity: 88 }, { tag: 'hustle', popularity: 85 },
      { tag: 'entrepreneurlife', popularity: 82 }, { tag: 'businessowner', popularity: 80 }, { tag: 'smallbusiness', popularity: 78 },
      { tag: 'leadership', popularity: 76 }, { tag: 'ceo', popularity: 74 }, { tag: 'money', popularity: 72 },
      { tag: 'businessmindset', popularity: 70 }, { tag: 'startuplife', popularity: 68 }, { tag: 'grind', popularity: 65 },
      { tag: 'wealth', popularity: 63 }, { tag: 'invest', popularity: 60 }, { tag: 'businesstips', popularity: 58 },
      { tag: 'entrepreneurship', popularity: 55 }, { tag: 'networking', popularity: 52 }, { tag: 'sidehustle', popularity: 50 },
      { tag: 'financialfreedom', popularity: 48 }, { tag: 'growthmindset', popularity: 45 },
    ],
  },
  {
    name: 'marketing',
    keywords: ['marketing', 'digital', 'socialmedia', 'branding', 'seo', 'content', 'advertising', 'growth'],
    hashtags: [
      { tag: 'marketing', popularity: 95 }, { tag: 'digitalmarketing', popularity: 93 }, { tag: 'socialmediamarketing', popularity: 90 },
      { tag: 'branding', popularity: 88 }, { tag: 'contentmarketing', popularity: 85 }, { tag: 'seo', popularity: 83 },
      { tag: 'marketingtips', popularity: 80 }, { tag: 'socialmedia', popularity: 78 }, { tag: 'onlinemarketing', popularity: 76 },
      { tag: 'emailmarketing', popularity: 74 }, { tag: 'marketingstrategy', popularity: 72 }, { tag: 'advertising', popularity: 70 },
      { tag: 'growthhacking', popularity: 68 }, { tag: 'influencermarketing', popularity: 65 }, { tag: 'contentcreator', popularity: 63 },
      { tag: 'brandstrategy', popularity: 60 }, { tag: 'marketingdigital', popularity: 58 }, { tag: 'copywriting', popularity: 55 },
      { tag: 'ppc', popularity: 52 }, { tag: 'affiliatemarketing', popularity: 50 }, { tag: 'marketingagency', popularity: 48 },
    ],
  },
  {
    name: 'tech',
    keywords: ['tech', 'technology', 'coding', 'programming', 'developer', 'software', 'ai', 'web', 'app', 'computer'],
    hashtags: [
      { tag: 'technology', popularity: 96 }, { tag: 'tech', popularity: 94 }, { tag: 'coding', popularity: 92 },
      { tag: 'programming', popularity: 90 }, { tag: 'developer', popularity: 88 }, { tag: 'software', popularity: 85 },
      { tag: 'ai', popularity: 83 }, { tag: 'webdevelopment', popularity: 80 }, { tag: 'javascript', popularity: 78 },
      { tag: 'python', popularity: 76 }, { tag: 'machinelearning', popularity: 74 }, { tag: 'datascience', popularity: 72 },
      { tag: 'cybersecurity', popularity: 70 }, { tag: 'innovation', popularity: 68 }, { tag: 'startup', popularity: 65 },
      { tag: 'techlife', popularity: 63 }, { tag: 'gadgets', popularity: 60 }, { tag: 'appdevelopment', popularity: 58 },
      { tag: 'cloudcomputing', popularity: 55 }, { tag: 'blockchain', popularity: 52 }, { tag: 'iot', popularity: 50 },
      { tag: 'devops', popularity: 48 }, { tag: 'opensource', popularity: 45 },
    ],
  },
  {
    name: 'motivation',
    keywords: ['motivation', 'inspire', 'mindset', 'goals', 'dream', 'believe', 'positive', 'quotes', 'affirmation'],
    hashtags: [
      { tag: 'motivation', popularity: 98 }, { tag: 'inspiration', popularity: 95 }, { tag: 'motivationalquotes', popularity: 92 },
      { tag: 'mindset', popularity: 90 }, { tag: 'goals', popularity: 88 }, { tag: 'success', popularity: 86 },
      { tag: 'positivevibes', popularity: 84 }, { tag: 'believe', popularity: 82 }, { tag: 'nevergiveup', popularity: 80 },
      { tag: 'dreambig', popularity: 78 }, { tag: 'selfimprovement', popularity: 76 }, { tag: 'growthmindset', popularity: 74 },
      { tag: 'dailymotivation', popularity: 72 }, { tag: 'inspire', popularity: 70 }, { tag: 'keepgoing', popularity: 68 },
      { tag: 'motivational', popularity: 65 }, { tag: 'positivity', popularity: 63 }, { tag: 'mindfulness', popularity: 60 },
      { tag: 'selfcare', popularity: 58 }, { tag: 'affirmations', popularity: 55 }, { tag: 'goalsetting', popularity: 52 },
      { tag: 'hustle', popularity: 50 }, { tag: 'grind', popularity: 48 },
    ],
  },
  {
    name: 'nature',
    keywords: ['nature', 'outdoor', 'mountain', 'ocean', 'forest', 'wildlife', 'sunset', 'sunrise', 'earth', 'green'],
    hashtags: [
      { tag: 'nature', popularity: 98 }, { tag: 'naturephotography', popularity: 94 }, { tag: 'sunset', popularity: 92 },
      { tag: 'landscape', popularity: 90 }, { tag: 'mountains', popularity: 88 }, { tag: 'ocean', popularity: 86 },
      { tag: 'wildlife', popularity: 84 }, { tag: 'forest', popularity: 82 }, { tag: 'sunrise', popularity: 80 },
      { tag: 'outdoors', popularity: 78 }, { tag: 'earth', popularity: 76 }, { tag: 'flowers', popularity: 74 },
      { tag: 'sky', popularity: 72 }, { tag: 'trees', popularity: 70 }, { tag: 'naturelover', popularity: 68 },
      { tag: 'hiking', popularity: 65 }, { tag: 'beach', popularity: 63 }, { tag: 'garden', popularity: 60 },
      { tag: 'waterfall', popularity: 58 }, { tag: 'clouds', popularity: 55 }, { tag: 'green', popularity: 52 },
      { tag: 'earthday', popularity: 50 }, { tag: 'conservation', popularity: 48 },
    ],
  },
  {
    name: 'pets',
    keywords: ['pet', 'dog', 'cat', 'puppy', 'kitten', 'animal', 'doggo', 'kitty', 'furry'],
    hashtags: [
      { tag: 'pets', popularity: 95 }, { tag: 'dogsofinstagram', popularity: 94 }, { tag: 'catsofinstagram', popularity: 92 },
      { tag: 'dog', popularity: 90 }, { tag: 'cat', popularity: 88 }, { tag: 'puppy', popularity: 86 },
      { tag: 'kitten', popularity: 84 }, { tag: 'petlovers', popularity: 82 }, { tag: 'doglife', popularity: 80 },
      { tag: 'catlife', popularity: 78 }, { tag: 'doglover', popularity: 76 }, { tag: 'catlover', popularity: 74 },
      { tag: 'petsofinstagram', popularity: 72 }, { tag: 'puppylove', popularity: 70 }, { tag: 'dogstagram', popularity: 68 },
      { tag: 'catstagram', popularity: 65 }, { tag: 'furbaby', popularity: 63 }, { tag: 'adoptdontshop', popularity: 60 },
      { tag: 'petlife', popularity: 58 }, { tag: 'animallovers', popularity: 55 }, { tag: 'dogmom', popularity: 52 },
      { tag: 'catmom', popularity: 50 },
    ],
  },
  {
    name: 'art',
    keywords: ['art', 'artist', 'drawing', 'painting', 'illustration', 'sketch', 'creative', 'design', 'artwork'],
    hashtags: [
      { tag: 'art', popularity: 98 }, { tag: 'artist', popularity: 96 }, { tag: 'artwork', popularity: 94 },
      { tag: 'drawing', popularity: 92 }, { tag: 'painting', popularity: 90 }, { tag: 'illustration', popularity: 88 },
      { tag: 'sketch', popularity: 86 }, { tag: 'creative', popularity: 84 }, { tag: 'design', popularity: 82 },
      { tag: 'digitalart', popularity: 80 }, { tag: 'artoftheday', popularity: 78 }, { tag: 'instaart', popularity: 76 },
      { tag: 'artistsoninstagram', popularity: 74 }, { tag: 'watercolor', popularity: 72 }, { tag: 'acrylic', popularity: 70 },
      { tag: 'oilpainting', popularity: 68 }, { tag: 'contemporaryart', popularity: 65 }, { tag: 'abstractart', popularity: 63 },
      { tag: 'artgallery', popularity: 60 }, { tag: 'fineart', popularity: 58 }, { tag: 'artcollector', popularity: 55 },
      { tag: 'sketchbook', popularity: 52 }, { tag: 'procreate', popularity: 50 },
    ],
  },
  {
    name: 'music',
    keywords: ['music', 'song', 'singer', 'band', 'guitar', 'piano', 'dj', 'hiphop', 'rap', 'rock', 'pop'],
    hashtags: [
      { tag: 'music', popularity: 98 }, { tag: 'musician', popularity: 94 }, { tag: 'singer', popularity: 92 },
      { tag: 'song', popularity: 90 }, { tag: 'hiphop', popularity: 88 }, { tag: 'rap', popularity: 86 },
      { tag: 'rock', popularity: 84 }, { tag: 'guitar', popularity: 82 }, { tag: 'piano', popularity: 80 },
      { tag: 'dj', popularity: 78 }, { tag: 'newmusic', popularity: 76 }, { tag: 'musicproducer', popularity: 74 },
      { tag: 'songwriter', popularity: 72 }, { tag: 'beats', popularity: 70 }, { tag: 'livemusic', popularity: 68 },
      { tag: 'musicislife', popularity: 65 }, { tag: 'indie', popularity: 63 }, { tag: 'producer', popularity: 60 },
      { tag: 'musiclover', popularity: 58 }, { tag: 'spotify', popularity: 55 }, { tag: 'soundcloud', popularity: 52 },
      { tag: 'concert', popularity: 50 },
    ],
  },
  {
    name: 'gaming',
    keywords: ['gaming', 'game', 'gamer', 'videogames', 'playstation', 'xbox', 'nintendo', 'pc', 'esports', 'twitch'],
    hashtags: [
      { tag: 'gaming', popularity: 96 }, { tag: 'gamer', popularity: 94 }, { tag: 'videogames', popularity: 92 },
      { tag: 'playstation', popularity: 90 }, { tag: 'xbox', popularity: 88 }, { tag: 'nintendo', popularity: 86 },
      { tag: 'pcgaming', popularity: 84 }, { tag: 'twitch', popularity: 82 }, { tag: 'esports', popularity: 80 },
      { tag: 'gamingcommunity', popularity: 78 }, { tag: 'streamer', popularity: 76 }, { tag: 'gaminglife', popularity: 74 },
      { tag: 'ps5', popularity: 72 }, { tag: 'xboxseriesx', popularity: 70 }, { tag: 'nintendoswitch', popularity: 68 },
      { tag: 'fortnite', popularity: 65 }, { tag: 'minecraft', popularity: 63 }, { tag: 'valorant', popularity: 60 },
      { tag: 'retrogaming', popularity: 58 }, { tag: 'gamergirl', popularity: 55 }, { tag: 'gameplay', popularity: 52 },
      { tag: 'gamingsetup', popularity: 50 },
    ],
  },
  {
    name: 'health',
    keywords: ['health', 'wellness', 'healthy', 'nutrition', 'diet', 'mental', 'yoga', 'meditation', 'wellbeing'],
    hashtags: [
      { tag: 'health', popularity: 96 }, { tag: 'wellness', popularity: 94 }, { tag: 'healthy', popularity: 92 },
      { tag: 'healthylifestyle', popularity: 90 }, { tag: 'nutrition', popularity: 88 }, { tag: 'yoga', popularity: 86 },
      { tag: 'meditation', popularity: 84 }, { tag: 'mentalhealth', popularity: 82 }, { tag: 'selfcare', popularity: 80 },
      { tag: 'healthyfood', popularity: 78 }, { tag: 'wellbeing', popularity: 76 }, { tag: 'healthyliving', popularity: 74 },
      { tag: 'mindfulness', popularity: 72 }, { tag: 'diet', popularity: 70 }, { tag: 'cleaneating', popularity: 68 },
      { tag: 'mentalwellness', popularity: 65 }, { tag: 'holistichealth', popularity: 63 }, { tag: 'plantbased', popularity: 60 },
      { tag: 'weightloss', popularity: 58 }, { tag: 'healthcoach', popularity: 55 }, { tag: 'stressrelief', popularity: 52 },
      { tag: 'anxietyrelief', popularity: 50 },
    ],
  },
  {
    name: 'lifestyle',
    keywords: ['lifestyle', 'life', 'daily', 'routine', 'living', 'home', 'decor', 'minimalist', 'aesthetic'],
    hashtags: [
      { tag: 'lifestyle', popularity: 96 }, { tag: 'lifestyleblogger', popularity: 92 }, { tag: 'dailylife', popularity: 90 },
      { tag: 'aesthetic', popularity: 88 }, { tag: 'minimalist', popularity: 86 }, { tag: 'homedecor', popularity: 84 },
      { tag: 'interior', popularity: 82 }, { tag: 'cozy', popularity: 80 }, { tag: 'morningroutine', popularity: 78 },
      { tag: 'lifestylephotography', popularity: 76 }, { tag: 'slowliving', popularity: 74 }, { tag: 'simpleliving', popularity: 72 },
      { tag: 'homedesign', popularity: 70 }, { tag: 'interiordesign', popularity: 68 }, { tag: 'scandinavian', popularity: 65 },
      { tag: 'bohostyle', popularity: 63 }, { tag: 'hygge', popularity: 60 }, { tag: 'lifestylegoals', popularity: 58 },
      { tag: 'everydaylife', popularity: 55 }, { tag: 'livingroom', popularity: 52 }, { tag: 'bedroom', popularity: 50 },
    ],
  },
  {
    name: 'education',
    keywords: ['education', 'learn', 'study', 'student', 'teacher', 'school', 'university', 'college', 'knowledge'],
    hashtags: [
      { tag: 'education', popularity: 94 }, { tag: 'learning', popularity: 92 }, { tag: 'student', popularity: 90 },
      { tag: 'study', popularity: 88 }, { tag: 'teacher', popularity: 86 }, { tag: 'school', popularity: 84 },
      { tag: 'university', popularity: 82 }, { tag: 'knowledge', popularity: 80 }, { tag: 'studygram', popularity: 78 },
      { tag: 'onlinelearning', popularity: 76 }, { tag: 'elearning', popularity: 74 }, { tag: 'studymotivation', popularity: 72 },
      { tag: 'teachersofinstagram', popularity: 70 }, { tag: 'college', popularity: 68 }, { tag: 'studytips', popularity: 65 },
      { tag: 'edtech', popularity: 63 }, { tag: 'stem', popularity: 60 }, { tag: 'homework', popularity: 58 },
      { tag: 'classroom', popularity: 55 }, { tag: 'studentlife', popularity: 52 }, { tag: 'learneveryday', popularity: 50 },
    ],
  },
  {
    name: 'sports',
    keywords: ['sports', 'football', 'basketball', 'soccer', 'baseball', 'tennis', 'athlete', 'nba', 'nfl'],
    hashtags: [
      { tag: 'sports', popularity: 96 }, { tag: 'football', popularity: 94 }, { tag: 'basketball', popularity: 92 },
      { tag: 'soccer', popularity: 90 }, { tag: 'nba', popularity: 88 }, { tag: 'nfl', popularity: 86 },
      { tag: 'athlete', popularity: 84 }, { tag: 'baseball', popularity: 82 }, { tag: 'tennis', popularity: 80 },
      { tag: 'sportsphotography', popularity: 78 }, { tag: 'sportslife', popularity: 76 }, { tag: 'gameday', popularity: 74 },
      { tag: 'champion', popularity: 72 }, { tag: 'teamwork', popularity: 70 }, { tag: 'training', popularity: 68 },
      { tag: 'sportsnews', popularity: 65 }, { tag: 'mma', popularity: 63 }, { tag: 'boxing', popularity: 60 },
      { tag: 'running', popularity: 58 }, { tag: 'marathon', popularity: 55 }, { tag: 'swimming', popularity: 52 },
    ],
  },
  {
    name: 'wedding',
    keywords: ['wedding', 'bride', 'groom', 'marriage', 'engaged', 'bridal', 'weddingday', 'ceremony'],
    hashtags: [
      { tag: 'wedding', popularity: 96 }, { tag: 'bride', popularity: 94 }, { tag: 'weddingday', popularity: 92 },
      { tag: 'weddingphotography', popularity: 90 }, { tag: 'weddingdress', popularity: 88 }, { tag: 'engaged', popularity: 86 },
      { tag: 'bridal', popularity: 84 }, { tag: 'groom', popularity: 82 }, { tag: 'weddingplanner', popularity: 80 },
      { tag: 'weddinginspo', popularity: 78 }, { tag: 'bridetobe', popularity: 76 }, { tag: 'weddingflowers', popularity: 74 },
      { tag: 'weddingcake', popularity: 72 }, { tag: 'weddinginspiration', popularity: 70 }, { tag: 'marriage', popularity: 68 },
      { tag: 'weddingvenue', popularity: 65 }, { tag: 'bridesmaids', popularity: 63 }, { tag: 'weddingideas', popularity: 60 },
      { tag: 'engagement', popularity: 58 }, { tag: 'weddingring', popularity: 55 }, { tag: 'honeymoon', popularity: 52 },
    ],
  },
  {
    name: 'realestate',
    keywords: ['realestate', 'property', 'home', 'house', 'realtor', 'apartment', 'mortgage', 'investment'],
    hashtags: [
      { tag: 'realestate', popularity: 95 }, { tag: 'realtor', popularity: 93 }, { tag: 'property', popularity: 90 },
      { tag: 'home', popularity: 88 }, { tag: 'house', popularity: 86 }, { tag: 'forsale', popularity: 84 },
      { tag: 'homesweethome', popularity: 82 }, { tag: 'dreamhome', popularity: 80 }, { tag: 'realestateinvesting', popularity: 78 },
      { tag: 'realestateagent', popularity: 76 }, { tag: 'househunting', popularity: 74 }, { tag: 'newhome', popularity: 72 },
      { tag: 'apartment', popularity: 70 }, { tag: 'mortgage', popularity: 68 }, { tag: 'investment', popularity: 65 },
      { tag: 'luxuryhomes', popularity: 63 }, { tag: 'openhouse', popularity: 60 }, { tag: 'homebuyer', popularity: 58 },
      { tag: 'propertyinvestment', popularity: 55 }, { tag: 'firsttimehomebuyer', popularity: 52 }, { tag: 'homeforsale', popularity: 50 },
    ],
  },
  {
    name: 'parenting',
    keywords: ['parenting', 'mom', 'dad', 'baby', 'kids', 'family', 'toddler', 'motherhood', 'fatherhood'],
    hashtags: [
      { tag: 'parenting', popularity: 94 }, { tag: 'mom', popularity: 92 }, { tag: 'momlife', popularity: 90 },
      { tag: 'baby', popularity: 88 }, { tag: 'kids', popularity: 86 }, { tag: 'family', popularity: 84 },
      { tag: 'motherhood', popularity: 82 }, { tag: 'dad', popularity: 80 }, { tag: 'dadlife', popularity: 78 },
      { tag: 'toddler', popularity: 76 }, { tag: 'newborn', popularity: 74 }, { tag: 'parentingtips', popularity: 72 },
      { tag: 'familytime', popularity: 70 }, { tag: 'momblogger', popularity: 68 }, { tag: 'babygirl', popularity: 65 },
      { tag: 'babyboy', popularity: 63 }, { tag: 'pregnancy', popularity: 60 }, { tag: 'fatherhood', popularity: 58 },
      { tag: 'parenthood', popularity: 55 }, { tag: 'kidsactivities', popularity: 52 }, { tag: 'sahm', popularity: 50 },
    ],
  },
  {
    name: 'diy',
    keywords: ['diy', 'craft', 'handmade', 'homemade', 'project', 'upcycle', 'woodworking', 'sewing'],
    hashtags: [
      { tag: 'diy', popularity: 96 }, { tag: 'handmade', popularity: 94 }, { tag: 'craft', popularity: 92 },
      { tag: 'doityourself', popularity: 90 }, { tag: 'crafts', popularity: 88 }, { tag: 'homemade', popularity: 86 },
      { tag: 'diyprojects', popularity: 84 }, { tag: 'handcrafted', popularity: 82 }, { tag: 'woodworking', popularity: 80 },
      { tag: 'sewing', popularity: 78 }, { tag: 'upcycle', popularity: 76 }, { tag: 'crafting', popularity: 74 },
      { tag: 'diyhomedecor', popularity: 72 }, { tag: 'makersgonnamake', popularity: 70 }, { tag: 'diycrafts', popularity: 68 },
      { tag: 'handmadewithlove', popularity: 65 }, { tag: 'cricut', popularity: 63 }, { tag: 'knitting', popularity: 60 },
      { tag: 'crochet', popularity: 58 }, { tag: 'etsy', popularity: 55 }, { tag: 'maker', popularity: 52 },
    ],
  },
  {
    name: 'books',
    keywords: ['book', 'reading', 'bookstagram', 'author', 'novel', 'library', 'literature', 'write', 'writer'],
    hashtags: [
      { tag: 'books', popularity: 95 }, { tag: 'bookstagram', popularity: 93 }, { tag: 'reading', popularity: 92 },
      { tag: 'booklover', popularity: 90 }, { tag: 'bookworm', popularity: 88 }, { tag: 'author', popularity: 86 },
      { tag: 'novel', popularity: 84 }, { tag: 'library', popularity: 82 }, { tag: 'bookish', popularity: 80 },
      { tag: 'bookrecommendations', popularity: 78 }, { tag: 'readersofinstagram', popularity: 76 }, { tag: 'bookclub', popularity: 74 },
      { tag: 'writer', popularity: 72 }, { tag: 'writersofinstagram', popularity: 70 }, { tag: 'literature', popularity: 68 },
      { tag: 'bookreview', popularity: 65 }, { tag: 'bookaddict', popularity: 63 }, { tag: 'currentlyreading', popularity: 60 },
      { tag: 'fiction', popularity: 58 }, { tag: 'nonfiction', popularity: 55 }, { tag: 'bookshelf', popularity: 52 },
    ],
  },
  {
    name: 'comedy',
    keywords: ['comedy', 'funny', 'humor', 'meme', 'joke', 'laugh', 'lol', 'hilarious', 'standup'],
    hashtags: [
      { tag: 'funny', popularity: 98 }, { tag: 'memes', popularity: 96 }, { tag: 'comedy', popularity: 94 },
      { tag: 'humor', popularity: 92 }, { tag: 'lol', popularity: 90 }, { tag: 'meme', popularity: 88 },
      { tag: 'hilarious', popularity: 86 }, { tag: 'joke', popularity: 84 }, { tag: 'laugh', popularity: 82 },
      { tag: 'funnymemes', popularity: 80 }, { tag: 'dankmemes', popularity: 78 }, { tag: 'comedyvideos', popularity: 76 },
      { tag: 'standup', popularity: 74 }, { tag: 'jokes', popularity: 72 }, { tag: 'funnyvideos', popularity: 70 },
      { tag: 'comedyclub', popularity: 68 }, { tag: 'sarcasm', popularity: 65 }, { tag: 'relatable', popularity: 63 },
      { tag: 'viral', popularity: 60 }, { tag: 'trending', popularity: 58 }, { tag: 'comedians', popularity: 55 },
    ],
  },
];

export const trendingHashtags: Hashtag[] = [
  { tag: 'trending', popularity: 98 }, { tag: 'viral', popularity: 97 }, { tag: 'fyp', popularity: 96 },
  { tag: 'foryou', popularity: 95 }, { tag: 'foryoupage', popularity: 94 }, { tag: 'explore', popularity: 93 },
  { tag: 'reels', popularity: 92 }, { tag: 'reelsinstagram', popularity: 90 }, { tag: 'tiktok', popularity: 88 },
  { tag: 'instagood', popularity: 86 }, { tag: 'photooftheday', popularity: 85 }, { tag: 'love', popularity: 84 },
  { tag: 'beautiful', popularity: 82 }, { tag: 'happy', popularity: 80 }, { tag: 'followme', popularity: 78 },
  { tag: 'like4like', popularity: 76 }, { tag: 'picoftheday', popularity: 74 }, { tag: 'instadaily', popularity: 72 },
  { tag: 'amazing', popularity: 70 }, { tag: 'instalike', popularity: 68 },
];

export const platformLimits: Record<string, number> = {
  instagram: 30,
  twitter: 5,
  tiktok: 8,
  linkedin: 5,
};

export const commonSuffixes = ['tips', 'life', 'goals', 'lover', 'daily', 'community', 'world', 'vibes', 'style', 'inspo', 'motivation', 'of the day'];
