import type { Metadata } from 'next';
import { HashtagGenerator } from '@/components/tools/HashtagGenerator';
import { AdSlot } from '@/components/ui/AdSlot';
import { FAQ } from '@/components/ui/FAQ';
import { FaqSchema } from '@/components/seo/FaqSchema';
import { RelatedTools } from '@/components/ui/RelatedTools';
import { tools } from '@/lib/tools-data';

export const metadata: Metadata = {
  title: 'Free Hashtag Generator - Instagram, Twitter, TikTok | SocialMediaTools.one',
  description: 'Generate trending hashtags for Instagram, Twitter, TikTok, and LinkedIn. 500+ hashtags across 25+ niches with platform-specific limits. Free, no signup required.',
  keywords: 'hashtag generator, instagram hashtags, twitter hashtags, tiktok hashtags, trending hashtags, hashtag finder, social media hashtags',
  openGraph: {
    title: 'Free Hashtag Generator for All Platforms | SocialMediaTools.one',
    description: 'Generate trending hashtags for Instagram, Twitter, TikTok, and LinkedIn instantly.',
    url: 'https://socialmediatools.one/hashtag-generator',
    type: 'website',
  },
  alternates: { canonical: 'https://socialmediatools.one/hashtag-generator' },
};

const faqs = [
  { question: 'How many hashtags should I use on Instagram?', answer: 'Instagram allows up to 30 hashtags per post. Research suggests using 20-30 relevant hashtags for maximum reach. Our generator automatically limits results to 30 hashtags when you select the Instagram preset, mixing popular, niche, and trending tags for optimal visibility.' },
  { question: 'What makes a good hashtag strategy?', answer: 'A strong hashtag strategy combines three types: popular hashtags (high volume for broad reach), niche hashtags (medium volume for targeted audiences), and branded hashtags (unique to your content). Our generator categorizes results into Popular, Niche, and Trending tabs to help you build this balanced mix.' },
  { question: 'How often should I change my hashtags?', answer: 'You should rotate your hashtags regularly to avoid being flagged as spam by platform algorithms. Aim to change at least 30-50% of your hashtags between posts. Use our generator to discover fresh hashtags for each post based on your specific topic.' },
  { question: 'Do hashtags work the same on every platform?', answer: 'No, each platform has different hashtag best practices. Instagram supports up to 30, Twitter works best with 1-3, TikTok recommends 3-5, and LinkedIn performs well with 3-5 professional hashtags. Our platform presets automatically adjust the count for each network.' },
  { question: 'Are these hashtags free to use?', answer: 'Yes, all hashtags generated by our tool are completely free to use on any platform. The tool runs entirely in your browser with no data collection, no signup required, and no usage limits. Generate as many hashtags as you need.' },
];

export default function HashtagGeneratorPage() {
  const related = tools.filter((t) => t.slug !== 'hashtag-generator').slice(0, 3);
  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <FaqSchema items={faqs} />
      <AdSlot slot="hashtag-leaderboard" />

      <div className="mb-8">
        <h1 className="text-3xl md:text-4xl font-extrabold mb-3" style={{ color: 'var(--color-text-heading)' }}>Free Hashtag Generator</h1>
        <p className="text-lg" style={{ color: 'var(--color-text-secondary)' }}>Generate trending hashtags for Instagram, Twitter, TikTok, and LinkedIn. 500+ hashtags across 25+ niches.</p>
      </div>

      <HashtagGenerator />

      <AdSlot slot="hashtag-below-results" />

      <section className="mt-12 rounded-xl p-8" style={{ backgroundColor: 'var(--color-bg-card)', border: '1px solid var(--color-border)' }}>
        <h2 className="text-2xl font-bold mb-6" style={{ color: 'var(--color-text-heading)' }}>How to Use the Hashtag Generator</h2>
        <div className="space-y-4 leading-relaxed" style={{ color: 'var(--color-text-secondary)' }}>
          <p>Hashtags are one of the most powerful tools for increasing your social media reach and discoverability. When used strategically, they connect your content with users who are actively searching for topics related to your posts. Our free hashtag generator simplifies this process by providing relevant, trending hashtags tailored to your specific content and platform.</p>
          <h3 className="text-xl font-semibold" style={{ color: 'var(--color-text-heading)' }}>Step 1: Enter Your Topic</h3>
          <p>Start by typing your post topic, keyword, or niche into the search field. The generator analyzes your input and matches it against our database of 500+ hashtags organized across 25+ categories including fitness, food, travel, fashion, photography, business, tech, and many more. The more specific your topic, the more targeted your hashtag suggestions will be.</p>
          <h3 className="text-xl font-semibold" style={{ color: 'var(--color-text-heading)' }}>Step 2: Filter by Category</h3>
          <p>Use the category checkboxes to narrow down your results. If you are posting about fitness content, select the fitness category to get hashtags specifically curated for workout posts, gym content, and health-related topics. You can select multiple categories to create a diverse hashtag mix that reaches different but related audiences.</p>
          <h3 className="text-xl font-semibold" style={{ color: 'var(--color-text-heading)' }}>Step 3: Choose Your Platform</h3>
          <p>Select your target platform from the preset buttons: Instagram (up to 30 hashtags), Twitter (3-5 hashtags), TikTok (5-8 hashtags), or LinkedIn (3-5 hashtags). Each platform has different optimal hashtag counts, and our presets automatically adjust the number of suggestions to match platform best practices for maximum engagement.</p>
          <h3 className="text-xl font-semibold" style={{ color: 'var(--color-text-heading)' }}>Step 4: Browse and Copy Results</h3>
          <p>Results are organized into three tabs: Popular (high-volume hashtags for broad reach), Niche (targeted hashtags for specific audiences), and Trending (currently hot hashtags). You can copy individual hashtags by clicking them or use the Copy All button to grab the entire set. The hashtag count display shows exactly how many tags you have selected.</p>
          <h3 className="text-xl font-semibold" style={{ color: 'var(--color-text-heading)' }}>Pro Tips for Hashtag Success</h3>
          <p>Mix popular and niche hashtags for the best results. Popular hashtags give you exposure to large audiences, while niche hashtags help you reach highly engaged, targeted users. Rotate your hashtags between posts to avoid algorithm penalties. Save different hashtag sets for different content themes, and always ensure your hashtags are relevant to your actual post content. Irrelevant hashtags can hurt your engagement rate and may result in shadowbanning on some platforms.</p>
        </div>
      </section>

      <AdSlot slot="hashtag-in-content" />

      <section className="mt-12">
        <h2 className="text-2xl font-bold mb-6" style={{ color: 'var(--color-text-heading)' }}>Frequently Asked Questions</h2>
        <FAQ items={faqs} />
      </section>

      <section className="mt-12">
        <RelatedTools tools={related} />
      </section>

      <AdSlot slot="hashtag-footer" />
    </div>
  );
}
